language: android
dist: trusty
install: ant deps
before_install:
    - openssl aes-256-cbc -K $encrypted_c0801aa05af4_key -iv $encrypted_c0801aa05af4_iv -in example_keystore.jks.enc -out example_keystore.jks -d
    - mkdir "$ANDROID_HOME/licenses" || true  
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - chmod +x gradlew  
    - ./gradlew dependencies || true
    
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - tools
     - platform-tools

    # The BuildTools version used by your project
    #- build-tools-28.0.3

    # The SDK version used to compile your project
    - android-29
    - echo yes | sdkmanager "build-tools;28.0.0"


    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
    
     
    
    #specifying Licenses
   licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
    
 

   
